### ISSUE TITLE
Yay GitHub!

### ISSUE THREAD

**Issue by egyptiankarim** [talentup/mobile-app#1]
Glad to see access and such is all sorted, @oracleot!

One thing: You might consider moving each of the apps (i.e., iOS, Android), into their own repositories. I think that'll make things easier to manage in the future should you have to handle separate teams contributing to different apps. Just a thought!

**Comment by oracleot** [comment]
Hi @egyptiankarim,

Thanks for the observation and so sorry I'm just seeing this.
We are using React Native for the app development for now and that's the folder structure for the framework. It uses a single codebase to push to both platforms (iOS and Android).
Do I still need to separate the concerns?

**Comment by egyptiankarim** [comment]
@oracleot no problem! I'm not familiar with the React conventions, but I think if you're following those you're probably all good. Thanks!
